#!/bin/bash
docker run -it --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --volume="/home/karsten/ROS/root:/root" --name ${MY_ROS_CONT_NAME}  kgo/ros_experiment

